# Site
title: Job Search Platform
bio: "A platform for your job search. All the tools you need to succeed! Kanban, Resume Generation, Keyword Stuffing"
description: "A platform for your job search. All the tools you need to succeed! Kanban, Resume Generation, Keyword Stuffing"
locale: en_US
baseurl: "/jobsearch" # the subpath of your site, e.g. /blog
# domain: bsneider.github.io # forces use of https by not specifying http
# url: "bsneider.github.io" # the base hostname & protocol for your site

# Social
analytics-id: "G-54TL3TLP6L"
# twitter: default
# facebook: default
# instagram: default
github: bsneider

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
utterances:
  repository: bsneider/jobsearch # GitHub username/repository eg. "daattali/beautiful-jekyll"
  issue-term: title # Mapping between blog posts and GitHub issues
  theme: github-light # Utterances theme
  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# # personal
# location: Los Angeles, CA
# phone: 310-318-5555
email: justhuckitstudios+jobsearch@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image: /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/blog/:title/"
      layout: post
      author:

# Jekyll
permalink: /blog/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
    old,
  ]
